# Configure Database
default: &default
  adapter: postgresql
  pool: 30
  timeout: 5000
  username: karthi
  password: 12345
development:
  <<: *default
  encoding: unicode
  database: blog_development
  host: localhost
test:
  <<: *default
  encoding: unicode
  database: blog_test
  host: localhost
production:
  <<: *default
  database: blog_production